# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceFinalisationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrence_number', models.IntegerField(default=0)),
                ('customer_number', models.IntegerField(default=0)),
                ('message_code', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=2000)),
                ('message_date', models.DateTimeField(verbose_name='message date')),
            ],
        ),
    ]
